### PR TITLE
Fixed setup issues

### PR DESCRIPTION
**Pull request by zee7han**
In this, I fixed the issue of runtime error of  "gem install mocha" that is also an open issue.
Also fixed the database authentication issue and database persistence issue.

### CODE REVIEW

**Comment by harie0x** [comment]
Hi @zee7han,

Mocha issue now got resolved. I can able to access the web GUI but, If i scan for any web target like scanme.nmap.org. I am finding the scan results as empty. can you please look in to this.
screen shot 2018-05-07 at 4 14 09 pm

**Comment by dkogue** [comment]
@harie0x  @zee7han 
did you find any work around on this issue. Having the same challenge , I would appreciate if you can help. Thanks in advance.

**Comment by zee7han** [comment]
@harie0x 
Can you provide me some more details information about this error?

**Comment by rgplvr** [comment]
Jackhammer v2 has been added to the master branch this pull request is obsolete now hence closing the same.

**Pull request closed without merging**
